root:
    path: /
    controller: App\Controller\Root::main

new:
    path: /new
    controller: App\Controller\Root::new


getWardrobe:
    path: /api/wardrobe
    controller: App\Controller\WardrobeController::getWardrobe
    methods: GET

createWardrobe:
    path: /api/wardrobe
    controller: App\Controller\WardrobeController::createWardrobe
    methods: POST|OPTIONS

removeWardrobe:
    path: /api/wardrobe/{id}
    controller: App\Controller\WardrobeController::removeWardrobe
    methods: DELETE|OPTIONS
  

getLocation:
    path: /api/location
    controller: App\Controller\LocationController::getLocation
    methods: GET

getAvailableLocation:
    path: /api/location/available
    controller: App\Controller\LocationController::getAvailableLocation
    methods: GET

updateLocation:
    path: /api/location/{country}-{city}
    controller: App\Controller\LocationController::updateLocation
    methods: POST|OPTIONS

removeLocation:
    path: /api/location
    controller: App\Controller\LocationController::removeLocation
    methods: DELETE|OPTIONS


getWeather:
    path: /api/weather
    controller: App\Controller\LocationController::getWeather
    methods: GET


getCategories:
    path: /api/category
    controller: App\Controller\CategoryController::getCategories
    methods: GET

createCategory:
    path: /api/category
    controller: App\Controller\CategoryController::createCategory
    methods: POST|OPTIONS

removeCategory:
    path: /api/category/{id}
    controller: App\Controller\CategoryController::removeCategory
    methods: DELETE|OPTIONS


getAllCloth:
    path: /api/cloth/{catId?}
    controller: App\Controller\ClothController::getAllCloth
    methods: GET

createCloth:
    path: /api/cloth
    controller: App\Controller\ClothController::createCloth
    methods: POST|OPTIONS

removeCloth:
    path: /api/cloth/{id}
    controller: App\Controller\ClothController::removeCloth
    methods: DELETE|OPTIONS

getCloth:
    path: /api/getCloth
    controller: App\Controller\ClothController::getCloth
    methods: GET

searchCloth:
    path: /api/cloth/search/{searchField}
    controller: App\Controller\ClothController::searchCloth
    methods: GET

