<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '4f10f2ff5eb2492069551c7842fa9350',
  'DATABASE_URL' => 'mysql://root@127.0.0.1:3306/smart_dressing?serverVersion=mariadb-10.4.17',
  'API_KEY' => '4cdfcec5cf0abbb5fa829a20afef9f28',
);
