#index:
#    path: /
#    controller: App\Controller\DefaultController::index

root:
    path: /
    controller: App\Controller\Root::main

createWardrobe:
    path: /create/wardrobe
    controller: App\Controller\Root::createWardrobe

new:
    path: /new
    controller: App\Controller\Root::new

removeWardrobe:
    path: /remove/wardrobe/{id}
    controller: App\Controller\Root::removeWardrobe
    
updateLocation:
    path: /update/location/{country}-{city}
    controller: App\Controller\Root::updateLocation

removeLocation:
    path: /remove/location/
    controller: App\Controller\Root::removeLocation

createCategory:
    path: /create/category
    controller: App\Controller\Root::createCategory

createCloth:
    path: /create/cloth
    controller: App\Controller\Root::createCloth
