root:
    path: /
    controller: App\Controller\Root::main

new:
    path: /new
    controller: App\Controller\Root::new

createWardrobe:
    path: /create/wardrobe
    controller: App\Controller\WardrobeController::createWardrobe

removeWardrobe:
    path: /remove/wardrobe/{id}
    controller: App\Controller\WardrobeController::removeWardrobe
    
updateLocation:
    path: /update/location/{country}-{city}
    controller: App\Controller\LocationController::updateLocation

removeLocation:
    path: /remove/location/
    controller: App\Controller\LocationController::removeLocation

createCategory:
    path: /create/category
    controller: App\Controller\CategoryController::createCategory

removeCategory:
    path: /remove/category/{id}
    controller: App\Controller\CategoryController::removeCategory

createCloth:
    path: /create/cloth
    controller: App\Controller\ClothController::createCloth

removeCloth:
    path: /remove/cloth/{id}
    controller: App\Controller\ClothController::removeCloth

getCloth:
    path: /getCloth
    controller: App\Controller\ClothController::getCloth

search:
    path: /search/{searchField}
    controller: App\Controller\ClothController::search

getClothByCategory:
    path: /filter/category/{id}
    controller: App\Controller\ClothController::getClothByCategory
