#index:
#    path: /
#    controller: App\Controller\DefaultController::index

root:
    path: /
    controller: App\Controller\Root::main

createWardrobe:
    path: /create/wardrobe
    controller: App\Controller\Root::createWardrobe

removeWardrobe:
    path: /remove/wardrobe/{id}
    controller: App\Controller\Root::removeWardrobe
    
updateLocation:
    path: /update/location/{country}-{city}
    controller: App\Controller\Root::updateLocation

removeLocation:
    path: /remove/location/
    controller: App\Controller\Root::removeLocation

test:
    path: /test
    controller: App\Controller\Test::list